{% set name = "dcc" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcc-{{ version }}.tar.gz
  sha256: 45bc3d006d3b377cdfd58baed5a4cf7d0bc2d898fa343d19be8179bb5fc968b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dcc = dcc.__main__:dcc

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - beautifulsoup4 >=4.0.0
    - ciecplib >=0.4.4
    - click >=7.0.0
    - html2text >=2018.1.9
    - python >=3.8
    - pytz >=2018.3
    - tomli >=2.0.0
    - tomli-w >=1.0.0

test:
  requires:
    - pip
    - pytest
    - requests-mock
  source_files:
    - tests/
  imports:
    - dcc
    - dcc.env
    - dcc.exceptions
    - dcc.parsers
    - dcc.records
    - dcc.sessions
    - dcc.testing
    - dcc.util
  commands:
    # Check requirements.
    - python -m pip check
    # Check CLI.
    - dcc --help
    - dcc archive --help
    - dcc convert --help
    - dcc list --help
    - dcc open --help
    - dcc open-file --help
    - dcc update --help
    - dcc view --help
    # Run tests.
    - python -m pytest tests

about:
  home: https://docs.ligo.org/sean-leavey/dcc/
  dev_url: https://git.ligo.org/sean-leavey/dcc/
  summary: Tools for interactive and programmatic access to the LIGO DCC.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SeanDS
    - duncanmmacleod
